### ISSUE TITLE
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds

### ISSUE THREAD

**Issue by godlatro** [MichaelQQ/dbfstream#6]
I try to use this module, but i get error
"stream-dbf" npm module works, but i need convert encoding.
Please help me improve this error
My code is:
`const dbfstream = require('dbfstream');
let fileName = 'ADDROB01.DBF';
var dbf = dbfstream(fileName, 'utf-8');
dbf.on('data', (data) => {
    console.log(data);
});`

internal/buffer.js:53
    throw new ERR_BUFFER_OUT_OF_BOUNDS();
    ^

RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds
    at boundsError (internal/buffer.js:53:11)
    at Buffer.readInt32LE (internal/buffer.js:277:5)
    at getHeader (C:\Users\a\Desktop\npm\node_modules\dbfstream\index.js:44:40)
    at ReadStream.readStream.once (C:\Users\a\Desktop\npm\node_modules\dbfstream\index.js:124:21)\index.js:124:21)
    at Object.onceWrapper (events.js:273:13)
    at ReadStream.emit (events.js:187:15)
    at emitReadable_ (_stream_readable.js:531:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by MichaelQQ** [comment]
Hi @godlatro, I just updated the module, you could try it again.

Thank you.
